server:
  port: 8000 #eureka运行的端口号
  address: 127.0.0.1

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-center
          uri: lb://order-center
          predicates:
            - Path=/order-center/**
          filters:
            - StripPrefix=1
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/user-center/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: 127.0.0.1
    port: 9000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka #注册中心地址，其它服务需要注册到该地址