server:
  port: 8001 #eureka运行的端口号
  address: 127.0.0.1

spring:
  application:
    name: user-center

eureka:
  instance:
      hostname: 127.0.0.1
      port: 9000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka #注册中心地址，其它服务需要注册到该地址